apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: hippo
spec:
  customReplicationTLSSecret:
    name: m1-db-client-crunchyrepl
  customTLSSecret:
    name: m1-postgres-server