namespace: postgres-operator

resources:
  - postgres.yaml


patchesStrategicMerge:
  - ibm/postgres-user.yaml
  - ibm/pgbouncer.yaml
  - ibm/labels.yaml
  - ibm/annotations.yaml
  - ibm/bouncer-affinity.yaml
  - ibm/pg-config.yaml
  - ibm/pgbackrest-resouces.yaml
  - ibm/pgbouncer-resources.yaml
  - ibm/pgbouncer-config.yaml
