apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name:  m1-db-client-crunchyrepl
spec:
  # Secret names are always required.
  secretName:  m1-db-client-crunchyrepl
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
    - hippo-org
  # The use of the common name field has been deprecated since 2000 and is
  # discouraged from being used.
  commonName: _crunchyrepl
  isCA: false
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
    - digital signature
    - key encipherment
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
  - _crunchyrepl
  issuerRef:
    Kind:  Issuer
    Name:  m1-ca
