apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: hippo
spec:
  proxy:
    pgBouncer:
      image: apic-dev-docker-local.artifactory.swg-devops.com/nihar/crunchy-pgbouncer:ubi8-5.2.0-0
      replicas: 3
