apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: hippo
spec:
  backups:
    pgbackrest:
      configuration:
        - secret:
            name: local-minio-s3-creds
      manual:
        repoName: repo1
        options:
          - --type=full
      global:
        repo1-path: /pgo/hippo-2022-10-04:22:17:32/repo1
        repo1-s3-uri-style: path
      repos:
        - name: repo1
          schedules:
            full: "*/10 * * * *"
          s3:
            bucket: "nihar"
            endpoint: "minio.minio.svc.cluster.local"
            region: "us-east-1"
