apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: hippo
spec:
  backups:
    pgbackrest:
      global:
        repo1-retention-full: "2"
        repo1-retention-full-type: count
        # repo1-retention-full: "1"
        # repo1-retention-full-type: time
      manual:
        repoName: repo1
        options:
         - --type=full
      repos:
        - name: repo1
          schedules:
            full: "50 1 * * *"
          volume:
            volumeClaimSpec:
              accessModes:
                - "ReadWriteOnce"
              resources:
                requests:
                  storage: 1Gi