apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: hippo
spec:
  backups:
    pgbackrest:
      configuration:
        - secret:
            name: aws-s3-creds
      global:
        repo1-path: /m1/postgres-operator/hippo-2022-08-13:01:08:47/repo1
      repos:
        - name: repo1
          s3:
            bucket: "niharns-cert-1"
            endpoint: "s3.eu-west-1.amazonaws.com"
            region: "eu-west-1"
