apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: hippo
spec:
  backups:
    pgbackrest:
      configuration:
        - secret:
            name: aws-s3-creds
      manual:
        repoName: repo1
        options:
          - --type=full
      global:
        repo1-path: /m1/postgres-operator/postgresdb/hippo-2022-09-17:02:15:48/repo1
        # repo1-retention-full: "2"
        # repo1-retention-full-type: count
        # repo1-retention-full: "1"
        # repo1-retention-full-type: time
      repos:
        - name: repo1
          # schedules:
          #   full: "*/10 * * * *"
          s3:
            bucket: "nihar-crunchy-v5"
            endpoint: "s3.amazonaws.com"
            region: "us-west-1"
