apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: hippo
spec:
  backups:
    pgbackrest:
      configuration:
        - secret:
            name: aws-s3-creds
      manual:
        repoName: repo1
        options:
          - --type=full
      global:
        repo1-path: /pgo/hippo-2022-10-04:22:17:32/repo1
        # repo2-path: /pgo/hippo-2022-09-27:01:06:06/repo2
        # repo3-path: /pgo/hippo-2022-09-27:01:06:06/repo3
        # repo1-retention-full: "2"
        # repo1-retention-full-type: count
        # repo1-retention-full: "1"
        # repo1-retention-full-type: time
      repos:
        # - name: repo3
        #   schedules:
        #     full: "*/10 * * * *"
        #   s3:
        #     bucket: "nihar-crunchy-v5"
        #     endpoint: "s3.amazonaws.com"
        #     region: "us-west-1"
        # - name: repo2
        #   schedules:
        #     full: "*/40 * * * *"
        #   s3:
        #     bucket: "nihar-crunchy-v5"
        #     endpoint: "s3.amazonaws.com"
        #     region: "us-west-1"
        - name: repo1
          schedules:
            full: "*/50 * * * *"
          s3:
            bucket: "nihar-crunchy-v5"
            endpoint: "s3.amazonaws.com"
            region: "us-west-1"
