apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: hippo
spec:
  backups:
    pgbackrest:
      restore:
        enabled: true
        repoName: repo1
        options:
        - --type=immediate
        #- --set=20220902-052528F # 3 rows
        #- --set=20220902-052924F # 9 rows 
        - --set=20220902-054021F  # 0 rows
        #- --set=20220902-033247F # 13 rows